ДЗ 2
htmlacademy-ecmascript/2102701-cinemaddict-18 pull request #4
Opened 2022-08-27 11:59 UTC by zuxzux

2022-08-27 12:45 UTC, senchkim commented on src/main.js
> +contentPresenter.init(siteMainElement, filmsModel, commentsModel);
даю подсказку, вот по смотри на модель данных!

https://github.com/thirdbyron/Vanilla-JavaScript-OOP-Project-MoviesToWatch/blob/module2-task1/src/mock/generate-comment-fish.js

2022-08-27 12:45 UTC, senchkim commented on src/presenter/content-presenter.js
>      render(new ShowMoreButtonView(), this.filmListComponent.getElement());
Презентер для модели!

https://github.com/thirdbyron/Vanilla-JavaScript-OOP-Project-MoviesToWatch/blob/module2-task1/src/presenter/popup-comments-presenter.js

2022-08-27 12:45 UTC, senchkim commented on src/view/film-card-view.js
>    getElement() {
дело не сколько в коде, изучи как выстроена взаимосвязь 👍

2022-08-31 13:33 UTC, VAnastasia requested changes

2022-08-31 13:33 UTC, VAnastasia commented on src/mock/const.js
> +  '../images/posters/the-man-with-the-golden-arm.jpg'
пути до картинок надо сделать относительно папки build, то есть так ./images/posters/the-man-with-the-golden-arm.jpg

2022-08-31 13:33 UTC, VAnastasia commented on src/mock/const.js
> +  '../images/emoji/smile.png'
./images/emoji/smile.png

2022-08-31 13:33 UTC, VAnastasia commented on src/view/film-details-view.js
> +                  <span class="film-details__genre">${filmInfo.genre}</span></td>
для массивов можно map использовать 
filmInfo.genre.map((genre) => <span class="film-details__genre">${genre}</span></td>).join('')

2022-08-31 13:34 UTC, merged